import { SkillPath } from './data/types';
import { webFrontendTechOptions } from './data/web-frontend';
import { backendTechOptions } from './data/backend';
import { mobileTechOptions } from './data/mobile';
import { dataScienceTechOptions } from './data/data-science';
import { devopsTechOptions, fullStackTechOptions } from './data/devops-fullstack';
import { web3TechOptions, aiMlTechOptions, gameDevTechOptions, cybersecurityTechOptions, iotTechOptions } from './data/advanced-paths';

export * from './data/types';

export const skillPaths: SkillPath[] = [
  {
    id: 'web-frontend',
    title: 'Web Frontend Development',
    description: 'Master the art of building beautiful, interactive user interfaces for the web.',
    icon: '🎨',
    image: '/images/paths/web-frontend.jpg',
    color: 'from-emerald-400 to-indigo-600',
    difficulty: 'beginner',
    duration: '4-6 months',
    students: 142,
    rating: 4.8,
    techOptions: webFrontendTechOptions,
  },
  {
    id: 'backend-development',
    title: 'Backend Development',
    description: 'Build robust, scalable server-side applications and APIs.',
    icon: '⚙️',
    image: '/images/paths/backend.jpg',
    color: 'from-green-500 to-emerald-700',
    difficulty: 'intermediate',
    duration: '6-8 months',
    students: 95,
    rating: 4.7,
    techOptions: backendTechOptions,
  },
  {
    id: 'mobile-development',
    title: 'Mobile Development',
    description: 'Create native and cross-platform applications for iOS and Android.',
    icon: '📱',
    image: '/images/paths/mobile.jpg',
    color: 'from-teal-500 to-indigo-700',
    difficulty: 'intermediate',
    duration: '5-7 months',
    students: 76,
    rating: 4.6,
    techOptions: mobileTechOptions,
  },
  {
    id: 'data-science',
    title: 'Data Science & Analytics',
    description: 'Transform raw data into actionable insights using statistics and programming.',
    icon: '📊',
    image: '/images/paths/data-science.jpg',
    color: 'from-yellow-400 to-orange-500',
    difficulty: 'advanced',
    duration: '6-9 months',
    students: 43,
    rating: 4.9,
    techOptions: dataScienceTechOptions,
  },
  {
    id: 'devops',
    title: 'DevOps & Cloud',
    description: 'Master CI/CD, cloud infrastructure, and deployment automation.',
    icon: '☁️',
    image: '/images/paths/devops.jpg',
    color: 'from-emerald-500 to-cyan-600',
    difficulty: 'advanced',
    duration: '4-6 months',
    students: 31,
    rating: 4.5,
    techOptions: devopsTechOptions,
  },
  {
    id: 'fullstack',
    title: 'Full Stack Development',
    description: 'Become a complete developer by mastering both frontend and backend technologies.',
    icon: '🌐',
    image: '/images/paths/fullstack.jpg',
    color: 'from-red-500 to-orange-600',
    difficulty: 'advanced',
    duration: '8-12 months',
    students: 58,
    rating: 4.8,
    techOptions: fullStackTechOptions,
  },
  {
    id: 'web3',
    title: 'Web3 & Blockchain',
    description: 'Build decentralized applications and smart contracts.',
    icon: '⛓️',
    image: '/images/paths/web3.jpg',
    color: 'from-teal-600 to-emerald-600',
    difficulty: 'advanced',
    duration: '5-7 months',
    students: 27,
    rating: 4.7,
    techOptions: web3TechOptions,
  },
  {
    id: 'ai-ml',
    title: 'AI & Machine Learning',
    description: 'Build intelligent systems and neural networks.',
    icon: '🤖',
    image: '/images/paths/ai-ml.jpg',
    color: 'from-emerald-500 to-teal-700',
    difficulty: 'advanced',
    duration: '6-9 months',
    students: 34,
    rating: 4.9,
    techOptions: aiMlTechOptions,
  },
  {
    id: 'game-dev',
    title: 'Game Development',
    description: 'Create immersive 2D and 3D gaming experiences.',
    icon: '🎮',
    image: '/images/paths/game-dev.jpg',
    color: 'from-rose-500 to-red-700',
    difficulty: 'intermediate',
    duration: '6-8 months',
    students: 42,
    rating: 4.6,
    techOptions: gameDevTechOptions,
  },
  {
    id: 'cybersecurity',
    title: 'Cybersecurity',
    description: 'Learn to protect networks, systems, and programs from digital attacks.',
    icon: '🛡️',
    image: '/images/paths/cybersecurity.jpg',
    color: 'from-gray-700 to-slate-900',
    difficulty: 'advanced',
    duration: '6-9 months',
    students: 21,
    rating: 4.7,
    techOptions: cybersecurityTechOptions,
  },
  {
    id: 'iot',
    title: 'Internet of Things (IoT)',
    description: 'Connect and control physical devices through the internet.',
    icon: '🔌',
    image: '/images/paths/iot.jpg',
    color: 'from-cyan-500 to-teal-500',
    difficulty: 'intermediate',
    duration: '4-6 months',
    students: 18,
    rating: 4.5,
    techOptions: iotTechOptions,
  },
];
